### ISSUE TITLE
Please wait a few minutes before you try again , getting this error while fetching the comments?

### ISSUE THREAD

**Issue by purnima110895** [adw0rd/instagrapi#1270]
comments = cl_obj.media_comments(photo_id, 0)

Trying to get all the comments for the posts.
But its giving Please wait a few minutes before you try again. error.
Please help @adw0rd .

**Comment by adw0rd** [comment]
It's an Instagram block. To avoid it, you need to use multiple accounts and multiple proxies. Or use https://api.lamadava.com/docs

**Comment by igornazarov1991** [comment]
@adw0rd , why you suggest to use lamadava for Instagram? If I understand correctly, it is for TikTok.

**Comment by igornazarov1991** [comment]
@adw0rd, thanks for your answer! In order to bypass rate limits you suggested to use multiple accounts and multiple proxies or use `lamadava`. What is confusing for me is the fact that Instagram web version is able to load data (likes, comments, followers etc) without rate limits. What is the difference and how web resolves the limits? Do you have any ideas?
