### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by k9ber** [adw0rd/instagrapi#23]
Здравствуйте, будет ли реализация регистрации?

**Comment by adw0rd** [comment]
@magdake постараюсь реализовать на этой неделе

**Comment by hamid** [comment]
any news ?

**Comment by xoxoinstagram** [comment]
any enhancement?

**Comment by adw0rd** [comment]
@xoxoinstagram few donations, but you can support

https://www.buymeacoffee.com/adw0rd

![image](https://user-images.githubusercontent.com/546889/133671493-56683509-6c09-4222-9465-2e11dde144f0.jpeg)

**Comment by andresolbach** [comment]
Any progress? Will it get implemented in Instagrapi when the goal is reached?

**Comment by PrakashMahesh2729** [comment]
bro changed 100$ goal into 1000$ 🥹

**Comment by PrakashMahesh2729** [comment]
yes, you guys are right honestly, I know only the basics and intermediate level(maybe), and I want to learn and achieve that mastery level, believe me, I am interested, but my college and surroundings don't even have a basics to help me🥲

Coming from a poor country, that 1000$ is like my father's 3-month salary
I am using a second used laptop that is provided by the government
we do not have wifi facility in our village, using mobile data, and the internet is like heavy pricing

Every dought or comment I ask, there is always someone to say you should learn high-level mastery,well i tried
Seems like its time for me to quit coding and go back to work at some home maid works
i have had enough bullying, Good bye soldiers my dreams dies here, Continue your journey

**Comment by adw0rd** [comment]
@PrakashMahesh2729 I am from Russia, I started programming in 1998 on a Subor 8-bit computer, my family was poor and could not buy a normal computer

![image](https://github.com/adw0rd/instagrapi/assets/546889/4258e5d1-261f-40ac-b75d-5043dd54e3ee)


I programmed for free for many years, worked as a loader and security guard, any free time I either read books about programming or programmed

my development was like this:

basic 1998-1999
pascal 1999-2002
delphi 2002-2003
c/c++ 2003-2005 (my first job)
php 2004-2009 (earned since that time)
javascript 2004 - present
elisp 2009 - present
python 2009 - present
erlang 2012 - present
golang 2021 - 2022
swift 2021 - present

i also tried ocaml, julia, R, ruby, java, c#, perl, lua, elixir, haskell, lisp closure, crystal, rust

continue to develop or move to another country if it seems to you that in your country there is no opportunity to develop

**Comment by PrakashMahesh2729** [comment]
Well that's a very awesome listing, hopefully 1day I get atleast some of those
