### ISSUE TITLE
please help me with this

### ISSUE THREAD

**Issue by pythoncoderabc** [adw0rd/instagrapi#301]
I get this kinda error when i try to upload image with instagrapi
![Screenshot (1)](https://user-images.githubusercontent.com/86769298/127187415-0a53cc81-1dd5-4c78-b461-c41c624c0861.png)

**Comment by adw0rd** [comment]
@pythoncoderabc cannot reproduce 

![image](https://user-images.githubusercontent.com/546889/127195055-beff79db-0279-4528-aaf8-22b70cf8d9a1.png)

It is reproduced only by you, so either solve the problem yourself and send the solution as PR.
Or attach more information such as username, password and proxy

**Comment by adw0rd** [comment]
@pythoncoderabc and fill bug report form:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide a piece of code to reproduce the problem.

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version
 - instagrapi version
 - moveipy version if used
 - imagemagick version if used

**Additional context**
Add any other context about the problem here.
