### ISSUE TITLE
Photo Upload failed with the following response: <Response [400]>

### ISSUE THREAD

**Issue by MRV1N2** [adw0rd/instagrapi#318]
What do  I wrong?

cl = Client()
cl.login(username, password)

a = cl.user_info_by_username(username)
media = cl.photo_upload("D:\\a\\Bild1.png", "First Test Upload")   #ERROR

#Console Output:
# Photo Upload failed with the following response: <Response [400]>

**Comment by adw0rd** [comment]
@MRV1N2 cannot reproduce 
![image](https://user-images.githubusercontent.com/546889/128478249-255b04dd-29d4-4737-993b-5f6456436378.png)

Try to figure out the reasons for yourself, since only you have it reproduced. Perhaps your photo is not the correct resolution, or your IP is in the ban list of Instagram, etc.

**Comment by MRV1N2** [comment]
Okey, I'm sticking to the research, I'm not giving up that easily. I will post my solution in here.

P.s. adw0rd this is a very cool repository from you. Thank you
