### ISSUE TITLE
[BUG] Highlight info LoginRequired error

### ISSUE THREAD

**Issue by djbomber36** [adw0rd/instagrapi#741]
**Describe the bug**
When logging by SessionId and calling Client#highlight_info_v1 it returns a LoginRequired error and expires the SessionId

**To Reproduce**
```python
from instagrapi import Client

cl = Client()
cl.login_by_sessionid(sessionid="yoursessionid")

user_id = cl.user_id_from_username("instagram")
user_highlights = cl.user_highlights_v1(user_id=user_id)
cl.highlight_info_v1(user_highlights[0].pk) # This gives LoginRequired error
```

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/feed/reels_media/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\Downloads\instagrapi-master\util\a.py", line 8, in <module>
    cl.highlight_info_v1(user_highlights[0].pk)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\highlight.py", line 110, in highlight_info_v1
    result = self.private_request('feed/reels_media/', data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 323, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
```

**Expected behavior**
Return the Highlight object.

**Desktop:**
 - OS: Windows 11 21H2
 - Python version: 3.10.5
 - instagrapi version: 1.16.20

**Comment by djbomber36** [comment]
@adw0rd Logging with a sessionid generated on the web version of instagram works fine when downloading medias and normal stories but when trying to use Client#highlight_info_v1 it gives me the error mentioned above.

**Comment by adw0rd** [comment]
@djbomber36 it is possible that instagram does not check your session on all endpoints, if you can research the reasons and fix it, then I will gladly accept your PR

**Comment by djbomber36** [comment]
@adw0rd Don't know if this is the solution but it works so here it is.

I tried to generate a sessionid in a browser and used it across 4 different browser with no issues but when used in a request with a mobile user-agent it expires the sessionid and logout all the devices with that sessionid.

So then I tried generating a sessionid with a mobile user-agent and used it in the instagrapi library to login with Client#login_by_session_id and it worked fine.

**SOLUTION**
You can't use a sessionid generated with a web user-agent when using a mobile user-agent (instagrapi user-agent).
Generate a sessionid with instagrapi and use that instead.

**Comment by mowshon** [comment]
@djbomber36 Yes, that was exactly the same problem I had. If you use the `sessionid` from the browser cookies, **instagram removes that** `sessionid` when you call `highlight_info()`.

### Solution

```python
from instagrapi import Client

# First, log in to your account using your username and password.
cl = Client()
cl.login('user', 'password')

print(cl.sessionid) # output: abc123
```
Now you can use **sessionid** without having to authenticate.

```python
cl.login_by_sessionid("abc123")
```

**Comment by davidrodma** [comment]
I noticed that when you log in with a user using sessionid and it doesn't work due to LoginRequired, and you try to log in again with the same user using username and password, you will receive LoginRequired again. But it's not just for this user, but for all different users that you try to log in normally with username and password, without sessionid after this error. It's as if the first login_by_sessionid attempt that gave a LoginRequired error affected the server's memory, so that the next users who have nothing to do with the first user were affected by the first user's error, receiving a LoginRequired even though they tried to log in by username and password . Regardless of whether the sessionid is valid or not, it should not affect other users who have nothing to do with the story. It's an easy error to reproduce, it's just a wrong sessionid in login_by_sessionid, on the first attempt, and you'll receive a LoginRequired infinitely, even if it's for another different user trying to log in with username and password as long as you don't restart the server.
The solution I found is to restart the server or change the login, setting the relogin=True parameter, like this:


```
                if sessionid:
                  try:
                      cl.login_by_sessionid(sessionid=session_id))
                  except LoginRequired:
                      cl.login(username, password,relogin=True) 
                else:
                    try:
                        cl.login(username, password)
                    except LoginRequired:
                        cl.login(username, password,relogin=True) 
```
