### ISSUE TITLE
Implement location_search by name and id

### ISSUE THREAD

**Issue by adw0rd** [adw0rd/instagrapi#9]

**Comment by Sebsebzen** [comment]
Hi, is it possible to search for GEO coordinates yet?

**Comment by adw0rd** [comment]
location_search - by coordinates https://github.com/adw0rd/instagrapi/blob/master/instagrapi/location.py#L10
More examples here - https://github.com/adw0rd/instagrapi/blob/master/tests.py#L798

**Comment by jhd3197** [comment]
@adw0rd 
I ran into an issue when I was adding locations to (photo_upload) it's picking always a different location and it's because the function (location_info) doesn't return  Location.external_id and this force the function (location_build) to do a location_search base on the lat and lng so this causing the locations to be wrong most of the time or not perfect here is and example of location_search_pk and location_info

`from instagrapi import Client
import sys
import json


cl = Client()

loc=cl.location_info(319703195161335)
print(loc)

loc1=cl.location_search_pk(319703195161335)
print(loc1)`

![image](https://user-images.githubusercontent.com/13461850/106427513-8b6aab00-6435-11eb-898e-f12aa6df01ea.png)

I also added the function location_search_name(name) example 

`from instagrapi import Client
import sys
import json


cl = Client()

locs=cl.location_search_name("caracas")
print(locs)
`
return 

![image](https://user-images.githubusercontent.com/13461850/106427860-121f8800-6436-11eb-979d-02135d1d7b08.png)

Here is the fork with the changes 
https://github.com/jhd3197/instagrapi/commit/df025a1f54f9659908629e3f197030e882aecfeb

Best hope this can help

**Comment by adw0rd** [comment]
@jhd3197 You ran tests?

**Comment by jhd3197** [comment]
@adw0rd
I did and I got this:

![image](https://user-images.githubusercontent.com/13461850/106595859-2f318500-6522-11eb-9af9-662a33fd2353.png)

but I don't know how to debug this or how to check if those errors are coming from this change I also try testing this repository without making any change and I always get a login issue when I'm trying to test with docker even when I know the password it's correct 

![image](https://user-images.githubusercontent.com/13461850/106596605-4329b680-6523-11eb-87f5-304c4df3884f.png)

**Comment by adw0rd** [comment]
Added FbSearchMixin.fbsearch_places:

```
>>> cl.fbsearch_places('New York')[0].dict()
{'pk': 486560663,
 'name': 'New York City, N.Y.',
 'phone': '',
 'website': '',
 'category': '',
 'hours': {},
 'address': None,
 'city': None,
 'zip': None,
 'lng': -74.005891084671,
 'lat': 40.712701423445,
 'external_id': 267185200114218,
 'external_id_source': 'facebook_places'}
```
